var d=!1,e,f,h,i=1,j=d,l=0,n=[50,500,100,20],o=3,p,r=[100,400],s=10,t=4,u=-4,v=d,w=0,x=0,y=0,z=5,A=10,B=d,C=[],D=[],E=0;window.c=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};
function F(){y=1E3==y+1?0:y+1;3>o&&o++;f.clearRect(0,0,e.width,e.height);0>t?(G=r[0]-s,H=r[1]):0<t&&(G=r[0]+s-1,H=r[1]);0>u?(I=r[0],J=r[1]-s+1):0<u&&(I=r[0],J=r[1]+s-1);for(var a=0;a<h.length;a++){for(var b=0;b<D.length;b++)if(D[b].y<=h[a].y+20&&D[b].y>=h[a].y&&D[b].x>=h[a].x&&D[b].x<=h[a].x+50){D[b]=D[D.length-1];D.pop();K(a);break}if(h[a]){if(h[a].x<=G&&G<=h[a].x+50&&h[a].y<=H&&H<=h[a].y+20)t*=-0.8-Math.random()/2.5;else if(h[a].x<=I&&I<=h[a].x+50&&h[a].y<=J&&J<=h[a].y+20)u*=-0.8-Math.random()/
2.5;else continue;t=2.5>Math.abs(t)?0<=t?2.5:-2.5:t;K(a);break}}0<A&&(B&&0==y%10)&&(D.push(new L),A--);0==h.length&&j===d&&(j=!0,r[0]=100,r[1]=400,n[0]=50,n[1]=500,n[2]=100,n[3]=20,A=z=0,B=d,o=3,u=t=0,C=[],D=[],i++);for(a=0;a<h.length;a++)b=h[a],f.beginPath(),f.lineWidth=0,f.moveTo(b.x,b.y),f.lineTo(b.x+50,b.y),f.lineTo(b.x+50,b.y+20),f.lineTo(b.x,b.y+20),f.lineTo(b.x,b.y),f.fillStyle=b.color,f.stroke(),f.fill();a=r[0]-n[0];n[0]+=2*l;var b=n[0],g=n[1],k=n[2],q=n[3];0<z&&(0==t&&0==u)&&(r[0]=b+a);f.beginPath();
f.lineWidth=1;f.moveTo(b,g);f.lineTo(b+k,g);f.lineTo(b+k,g+q);f.lineTo(b,g+q);f.lineTo(b,g);f.fillStyle="#000";f.stroke();f.fill();a=r[0];b=r[1];a+s>=e.width?t*=-1:0>=a-s?t*=-1:b+s>=n[1]&&b+s<=n[1]+n[3]&&a>=n[0]&&a<=n[0]+n[2]&&3==o?(o=0,0==t&&2==E++&&(t=4*(0.5<=Math.random()?-1:1),E=0),v)?(k=h[Math.floor(Math.random()*h.length)],g=k.x+25-r[0],k=k.y+10-r[1],u=5*(-k/k),t=5*(-g/k)):0<z?t=u=0:u*=-0.8-Math.random()/2.5:0>=b-s?u*=-1:b+s>=e.height&&(r[0]=100,r[1]=400,t*=-1,u*=-1);f.beginPath();f.fillStyle=
"#3a8";f.arc(a,b,s,0,2*Math.PI,!0);f.closePath();f.fill();r[0]+=t;r[1]+=u;for(a=0;a<C.length;a++)C[a].y>e.height+100&&(C[a]=C[C.length-1],C.pop());for(var m in C){a=C[m];b=void 0;f.beginPath();switch(a.type){case 0:b=5;f.fillStyle="#fac";break;case 1:b=15;f.fillStyle="#0a0";break;case 2:b=25,f.fillStyle="#1ca"}f.arc(a.x,a.y,b,0,2*Math.PI,!0);f.closePath();f.fill();a.y+=5}for(m=0;m<D.length;m++)if(null==D[m]||void 0==D[m]||-100>D[m].y)D[m]=D[D.length-1],D.pop();for(var N in D)m=D[N],f.beginPath(),
f.arc(m.x,m.y,2,0,2*Math.PI,!0),f.closePath(),f.fill(),m.y-=5;window.c(function(){F()})}function M(a,b){var g=[100,500,1E3],k=Math.floor(Math.random()*g.length);this.x=a;this.y=b;this.a=g[k];this.type=k}function O(a,b,g){switch(a){case 0:this.color="#000";this.a=100;break;case 1:this.color="#f00";this.a=200;break;case 2:this.color="#0f0";this.a=500;0.5<=Math.random()&&(this.b=new M(b+25,g+10));break;case 3:this.color="#0ff",this.a=1E3}this.x=b;this.y=g}var G,H,I,J;
function K(a){h[a].b&&C.push(h[a].b);w+=h[a].a;if(w>x){var b=w;x=b;window.localStorage.setItem("highscore",b);document.getElementById("lblHighscore").innerHTML=b}document.getElementById("lblScore").innerHTML=w;h[a]=h[h.length-1];h.pop()}
function P(){var a=i;h=[];for(var b=0;50>b;b++){var g=100*Math.random(),k,q;switch(a){case 1:k=Math.floor(b/5);q=b%5;break;case 2:k=Math.floor(b/5);q=2*(b%5)+k%2;break;case 3:k=2*Math.floor(b/10)+0.5;q=b%10;break;case 4:k=Math.floor(b/5),q=2*(b%5)+0.5*(k%10)}5>g?g=3:15>g?g=2:35>g?g=1:100>g&&(g=0);h[b]=new O(g,52*k+5,22*q+5)}}
document.addEventListener("DOMContentLoaded",function(){e=document.getElementById("canvas");f=e.getContext("2d");P();F();x=window.localStorage.getItem("highscore");document.getElementById("lblHighscore").innerHTML=x;window.addEventListener("keydown",function(a){if(37==a.keyCode||39==a.keyCode)l=37==a.keyCode?-5:5,a.preventDefault(),a.stopPropagation(),p=a.keyCode;else if(32==a.keyCode&&(j?(j=d,u=-4,t=4,P(),E=0):0<z&&(0==u&&0==t)&&(u=-5,o=0,z--),0<A&&B==d))y=-1,B=!0},d);window.addEventListener("keyup",
function(a){if(p==a.keyCode&&(37==a.keyCode||39==a.keyCode))l=0;B&32==a.keyCode&&(B=d)},d)},d);function L(){var a=n[1]+n[3]/2;this.x=n[0]+n[2]/2;this.y=a};
