var e=!0,f=!1,g,h,i,k=1,l=f,m=0,o=[50,500,100,20],p=3,q,t=[100,400],u=10,v=4,w=-4,x=f,y=0,z=0,A=0,B=5,C=1E3,D=f,E=f,F=[],G=[],H=0,I=5;
document.addEventListener("DOMContentLoaded",function(){g=document.getElementById("canvas");h=g.getContext("2d");J();K();z=window.localStorage.getItem("highscore");document.getElementById("lblHighscore").innerHTML=z;window.addEventListener("keydown",function(a){if(37==a.keyCode||39==a.keyCode)m=37==a.keyCode?-5:5,a.preventDefault(),a.stopPropagation(),q=a.keyCode;else if(32==a.keyCode)if(l)l=f,w=-4,v=4,J(),H=0,E=f;else if(0<B&&(0==w&&0==v)&&(w=-5,p=0,B--,E=f),0<C&&D==f)A=-1,D=e},f);window.addEventListener("keyup",
function(a){if(q==a.keyCode&&(37==a.keyCode||39==a.keyCode))m=0;D&32==a.keyCode&&(D=f)},f)},f);window.c=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};
function K(){if(0==A%100){for(var a=0;a<G.length;a++)if(null==G[a]||void 0==G[a]||-100>G[a].y)G[a]=G[G.length-1],G.pop();for(a=0;a<F.length;a++)F[a].y>g.height+100&&(F[a]=F[F.length-1],F.pop())}A=1E3==A+1?0:A+1;3>p&&p++;h.clearRect(0,0,g.width,g.height);var d,b,j,n;0>v?(d=t[0]-u,b=t[1]):0<v&&(d=t[0]+u-1,b=t[1]);0>w?(j=t[0],n=t[1]-u+1):0<w&&(j=t[0],n=t[1]+u-1);for(a=0;a<i.length;a++){for(var r=0;r<G.length;r++)if(G[r].y<=i[a].y+20&&G[r].y>=i[a].y&&G[r].x>=i[a].x&&G[r].x<=i[a].x+50){G[r]=G[G.length-
1];G.pop();L(a);break}if(i[a]){if(i[a].x<=d&&d<=i[a].x+50&&i[a].y<=b&&b<=i[a].y+20)M();else if(i[a].x<=j&&j<=i[a].x+50&&i[a].y<=n&&n<=i[a].y+20)N();else continue;v=2.5>Math.abs(v)?0<=v?2.5:-2.5:v;L(a);break}}t[0]+u>=g.width?M():0>=t[0]-u?M():t[1]+u>=o[1]&&t[1]+u<=o[1]+o[3]&&t[0]>=o[0]&&t[0]<=o[0]+o[2]&&3==p?(p=0,0==v&&2==H++&&(v=4*(0.5<=Math.random()?-1:1),H=0),x)?(b=i[Math.floor(Math.random()*i.length)],d=b.x+25-t[0],b=b.y+10-t[1],w=5*(-b/b),v=5*(-d/b)):0<B?(v=w=0,t[1]=o[1]-10,E=e):N():0>=t[1]-u?
N():t[1]+u>=g.height&&(t[0]=100,t[1]=400,w=v=0,N(),M(),I--);0<C&&(D&&0==A%1)&&(G.push(new O),C--);0==i.length&&l===f&&(l=e,t[0]=100,t[1]=400,o[0]=50,o[1]=500,o[2]=100,o[3]=20,C=B=0,D=f,p=3,w=v=0,F=[],G=[],k++,E=f);for(d=0;d<i.length;d++)b=i[d],h.beginPath(),h.lineWidth=0,h.moveTo(b.x,b.y),h.lineTo(b.x+50,b.y),h.lineTo(b.x+50,b.y+20),h.lineTo(b.x,b.y+20),h.lineTo(b.x,b.y),h.fillStyle=b.color,h.stroke(),h.fill();d=t[0]-o[0];o[0]+=2*m;b=o[0];j=o[1];n=o[2];a=o[3];0<B&&(0==v&&0==w&&E)&&(t[0]=b+d);h.beginPath();
h.lineWidth=1;h.moveTo(b,j);h.lineTo(b+n,j);h.lineTo(b+n,j+a);h.lineTo(b,j+a);h.lineTo(b,j);h.fillStyle="#000";h.stroke();h.fill();d=t[0];b=t[1];h.beginPath();h.fillStyle="#3a8";h.arc(d,b,u,0,2*Math.PI,e);h.closePath();h.fill();t[0]+=v;t[1]+=w;for(var s in F)if(F[s]){d=F[s];b=void 0;h.beginPath();switch(d.type){case 0:b=5;h.fillStyle="#fac";break;case 1:b=15;h.fillStyle="#0a0";break;case 2:b=25,h.fillStyle="#1ca"}h.arc(d.x,d.y,b,0,2*Math.PI,e);h.closePath();h.fill();d.y+=5}for(var P in G)s=G[P],h.beginPath(),
h.arc(s.x,s.y,2,0,2*Math.PI,e),h.closePath(),h.fill(),s.y-=5;window.c(function(){K()})}function N(){w*=-0.8-Math.random()/2.5}function M(){v*=-0.8-Math.random()/2.5}function L(a){i[a].b&&F.push(i[a].b);y+=i[a].a;if(y>z){var d=y;z=d;window.localStorage.setItem("highscore",d);document.getElementById("lblHighscore").innerHTML=d}document.getElementById("lblScore").innerHTML=y;i[a]=i[i.length-1];i.pop()}
function J(){var a=k;i=[];for(var d=0;50>d;d++){var b=100*Math.random(),j,n;switch(a){case 1:j=Math.floor(d/5);n=d%5;break;case 2:j=Math.floor(d/5);n=2*(d%5)+j%2;break;case 3:j=2*Math.floor(d/10)+0.5;n=d%10;break;case 4:j=Math.floor(d/5),n=2*(d%5)+0.5*(j%10)}5>b?b=3:15>b?b=2:35>b?b=1:100>b&&(b=0);i[d]=new Q(b,52*j+5,22*n+5)}}
function Q(a,d,b){switch(a){case 0:this.color="#000";this.a=100;break;case 1:this.color="#f00";this.a=200;break;case 2:this.color="#0f0";this.a=500;0.5<=Math.random()&&(this.b=new R(d+25,b+10));break;case 3:this.color="#0ff",this.a=1E3}this.x=d;this.y=b;this.type=a}function R(a,d){var b=[100,500,1E3],j=Math.floor(Math.random()*b.length);this.x=a;this.y=d;this.a=b[j];this.type=j}function O(){var a=o[1]+o[3]/2;this.x=o[0]+o[2]/2;this.y=a};
